apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ssl
  labels:
    type: ingress
    ssl: enable
    app: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: home.netology.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-ng-ssl
              port:
                name: nginx
  tls:
  - hosts:
      - home.netology.local
    secretName: secret-tls
